"""empty message

Revision ID: d52a2a89dcf6
Revises: f1c210eaaa48
Create Date: 2024-07-04 10:02:15.266934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd52a2a89dcf6'
down_revision = 'f1c210eaaa48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expired', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.drop_column('expired')

    # ### end Alembic commands ###
